from pathlib import Path
from unittest.mock import patch

import pytest
from typer.testing import CliRunner

from clanguru.main import app
from clanguru.object_analyzer import ObjectDependencies, Symbol, SymbolLinkage

runner = CliRunner()


@pytest.mark.skip(reason="exploratory test")
def test_generate(tmp_path: Path) -> None:
    output_file = tmp_path / "output.md"
    result = runner.invoke(
        app,
        [
            "generate",
            "--source-file",
            "D:/ateliere/spled/src/power_signal_processing/test/test_power_signal_processing.cc",
            "--output-file",
            output_file.as_posix(),
            "--compilation-database",
            "D:/ateliere/spled/build/CustA/Disco/test/compile_commands.json",
        ],
    )
    assert result.exit_code == 0


def test_mock(tmp_path: Path) -> None:
    header_file = tmp_path / "test.h"
    header_file.write_text("""
    extern int add(int a, int b);
    """)
    source_file = tmp_path / "test.c"
    source_file.write_text("""
    #include "test.h"
    int calculate(int x, int y) {
        return add(x, y);
    }
    """)
    result = runner.invoke(
        app,
        [
            "mock",
            "--source-file",
            source_file.as_posix(),
            "--output-dir",
            tmp_path.as_posix(),
            "--symbol",
            "add",
            "--filename",
            "my_mock",
        ],
    )
    assert result.exit_code == 0

    for mock_file in ["my_mock.h", "my_mock.cc"]:
        assert (tmp_path / mock_file).exists()


def test_mock_strict_mode(tmp_path: Path) -> None:
    header_file = tmp_path / "test.h"
    header_file.write_text("""
    extern int add(int a, int b);
    """)
    source_file = tmp_path / "test.c"
    source_file.write_text("""
    #include "test.h"
    #include "non_existent.h"
    int calculate(int x, int y) {
        return add(x, y);
    }
    """)
    result = runner.invoke(
        app,
        [
            "mock",
            "--source-file",
            source_file.as_posix(),
            "--output-dir",
            tmp_path.as_posix(),
            "--symbol",
            "non_existent_function",
            "--filename",
            "my_mock",
            "--strict",
        ],
    )
    # Expect failure with aggregated error message directing user to log file.
    assert result.exit_code != 0
    assert "Mock generation for 'my_mock' failed" in str(result.exception)
    log_file = tmp_path / "my_mock.log"
    assert log_file.exists()
    log_content = log_file.read_text()
    # Ensure the log captures parsing error and missing symbol summary.
    assert "non_existent.h" in log_content  # parsing error recorded
    assert "missing_symbol:non_existent_function" in log_content or "non_existent_function" in log_content
    assert "status: failed" in log_content


def test_mock_with_partial_object_file_only(tmp_path: Path) -> None:
    # Create a simple object file with some symbols

    source_file = tmp_path / "test.c"
    source_file.write_text("""
    extern int add(int a, int b);
    extern void print_result(int result);
    """)

    # Create a mock partial object file - this is a simplified approach
    # In reality, this would be generated by a compiler, but for testing we'll mock the nm output
    partial_obj_file = tmp_path / "test.o"
    partial_obj_file.write_bytes(b"fake object file content")

    # Mock the NmExecutor.run method to return expected symbols
    mock_object_data = ObjectDependencies(partial_obj_file)
    mock_object_data.symbols = [
        Symbol(name="add", linkage=SymbolLinkage.EXTERN),
        Symbol(name="print_result", linkage=SymbolLinkage.EXTERN),
        Symbol(name="_do_not_exist", linkage=SymbolLinkage.EXTERN),
    ]

    with patch("clanguru.main.NmExecutor.run", return_value=mock_object_data):
        result = runner.invoke(
            app,
            [
                "mock",
                "--source-file",
                source_file.as_posix(),
                "--output-dir",
                tmp_path.as_posix(),
                "--filename",
                "partial_mock",
                "--partial-object-file",
                partial_obj_file.as_posix(),
                "--exclude-symbol-pattern",
                "_*",
                "--strict",
            ],
        )

    assert result.exit_code == 0
    for mock_file in ["partial_mock.h", "partial_mock.cc", "partial_mock.log"]:
        assert (tmp_path / mock_file).exists()


def test_mock_without_symbols_or_partial_object_fails(tmp_path: Path) -> None:
    source_file = tmp_path / "test.c"
    source_file.write_text("""
    extern int add(int a, int b);
    """)

    result = runner.invoke(
        app,
        [
            "mock",
            "--source-file",
            source_file.as_posix(),
            "--output-dir",
            tmp_path.as_posix(),
            "--filename",
            "no_symbols_mock",
        ],
    )

    assert result.exit_code == 1
    assert "No symbols provided" in str(result.exception)


def test_mock_with_config_file(tmp_path: Path) -> None:
    source_file = tmp_path / "test.c"
    source_file.write_text("""
    extern int add(int a, int b);
    extern int print_result(int value);
    int add(int a, int b) { return a + b; }
    int print_result(int value) { printf("%d\\n", value); return 0; }
    """)

    config_file = tmp_path / "mock_config.yaml"
    config_file.write_text("""
strict: false
exclude_symbol_patterns:
  - "_*"
mock_type: gmock
""")

    result = runner.invoke(
        app,
        [
            "mock",
            "--source-file",
            source_file.as_posix(),
            "--symbol",
            "add",
            "--symbol",
            "print_result",
            "--symbol",
            "_internal_func",
            "--output-dir",
            tmp_path.as_posix(),
            "--filename",
            "config_mock",
            "--config-file",
            config_file.as_posix(),
        ],
    )
    assert result.exit_code == 0
    for mock_file in ["config_mock.h", "config_mock.cc", "config_mock.log"]:
        assert (tmp_path / mock_file).exists()

    # Check that the excluded symbol is mentioned in the log
    log_content = (tmp_path / "config_mock.log").read_text()
    assert "_internal_func : reason=excluded_by_pattern" in log_content
    assert "status: success" in log_content


@pytest.mark.skip(reason="exploratory test")
def test_debug_mock_behaviour() -> None:
    project_dir = Path("D:/ateliere/spledy")
    output_dir = Path("C:/temp")
    partial_object_file = project_dir.joinpath(".yanga/build/Disco/gtest/test_integrations_spled/test_integrations_spled_PC.o")
    compilation_db = project_dir.joinpath(".yanga/build/Disco/gtest/compile_commands.json")
    sources = [
        "components/spled/src/spled.c",
        "components/rte/src/rte.c",
        "components/brightness_controller/src/brightness_controller.c",
        "components/light_controller/src/light_controller.c",
        "components/main_control_knob/src/main_control_knob.c",
        "components/power_button/src/power_button.c",
        "components/power_signal_processing/src/power_signal_processing.c",
    ]
    result = runner.invoke(
        app,
        [
            "mock",
            "--filename",
            "mockup_test_integrations_spled",
            *[f"--source-file={project_dir.joinpath(source).as_posix()}" for source in sources],
            "--partial-object-file",
            partial_object_file.as_posix(),
            "--compilation-database",
            compilation_db.as_posix(),
            "--no-strict",
            "--exclude-symbol-pattern",
            "_*",
            "--output-dir",
            output_dir.as_posix(),
        ],
    )
    assert result.exit_code == 0
    for mock_file in ["mockup_test_integrations_spled.h", "mockup_test_integrations_spled.cc", "mockup_test_integrations_spled.log"]:
        assert (output_dir / mock_file).exists()

    # Check the log to verify the fix - no duplicate symbols
    log_content = (output_dir / "mockup_test_integrations_spled.log").read_text()
    print("=== LOG CONTENT ===")
    print(log_content)

    # Check for duplicate symbols in the mocked symbols section
    button_pressed_count = log_content.count("function ButtonInterfaceIsButtonPressed ->")
    button_init_count = log_content.count("function buttonInterface_init ->")

    print(f"ButtonInterfaceIsButtonPressed appears {button_pressed_count} times in log")
    print(f"buttonInterface_init appears {button_init_count} times in log")

    # After the fix, each symbol should appear exactly once
    assert button_pressed_count == 1, f"Expected ButtonInterfaceIsButtonPressed to appear exactly once, got {button_pressed_count}"
    assert button_init_count == 1, f"Expected buttonInterface_init to appear exactly once, got {button_init_count}"

    # Also check the generated header for no duplicates
    header_content = (output_dir / "mockup_test_integrations_spled.h").read_text()
    mock_method_button_count = header_content.count("MOCK_METHOD((boolean), ButtonInterfaceIsButtonPressed, (KeyCodes key));")
    mock_method_init_count = header_content.count("MOCK_METHOD((void), buttonInterface_init, ());")

    print(f"MOCK_METHOD for ButtonInterfaceIsButtonPressed appears {mock_method_button_count} times")
    print(f"MOCK_METHOD for buttonInterface_init appears {mock_method_init_count} times")

    assert mock_method_button_count == 1, f"Expected single MOCK_METHOD for ButtonInterfaceIsButtonPressed, got {mock_method_button_count}"
    assert mock_method_init_count == 1, f"Expected single MOCK_METHOD for buttonInterface_init, got {mock_method_init_count}"
